version: '3.9'

services:
  app:
    container_name: DinizIntelligence
    build:
      context: .
      dockerfile: Dockerfile
    image: dinizintel:1.0
    restart: always
    volumes:
      - .:/dados
    ports:
      - "2000:2000"